mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: user
  password: pass

template-gui:
  text:
    write-your-own-response: "Write your own response"
    custom-response-sign-header: "&f&nYour Response"
    uncategorized-sign-header: "&f&nYour dialogue"
  filler-item: white_stained_glass_pane
  inventory-name: "&lChoose an what type of dialogue do you want!"
  rows: 4
  cancel:
    enabled: true
    item: barrier
    position: 27
    name: "&cCancel"
    lore:
      - "&7Cancel our dialogue"

templates:
  OVERALL:
    gui:
      enabled: true
      item: green_concrete
      position: 10
      name: '&aOverall Statistics'
      lore:
        - '&fI can quickly grade how well you have been progressing on the server.'
    prompts:
      - prompt: Observation Skills
        worlds:
          NoMoon:
            feedback: I made a graphic of your progress on observation structure\n
      - prompt: Quests
        worlds:
          NoMoon:
            feedback: So far you have completed {} quests.
  SESSION:
    gui:
      enabled: true
      item: blue_concrete
      position: 12
      name: '&bSession Statistics'
      lore:
        - '&fI can quickly grade how you are doing today on the server.'
    prompts:
      - prompt: Observations
        worlds:
          NoMoon:
              feedback: Your observation score for today is {}. You should try some different observation types or look for some unique aspects of this planet.
      - prompt: Science Tools
        worlds:
          NoMoon:
            feedback: Your science tool score for today is {}. You should try some different science tools to see how this planet is different from Earth.
      - prompt: Exploration
        worlds:
          NoMoon:
            feedback: Your exploration score for today is {}. You should try exploraing different areas of the world to find some unique aspects of this planet.

  SCIENCE:
    gui:
      enabled: true
      item: orange_concrete
      position: 14
      name: '&6Science Facts'
      lore:
        - '&fI can discuss some science facts relevant to this world.'
    prompts:
      - prompt: Trees
        worlds:
          NoMoon:
            feedback: The trees are short and squat due to the extreme wind as a result of having no moon.
      - prompt: Moon
        worlds:
          NoMoon:
            feedback: There is no moon on this hypothetical world, try measuring the wind to see how this effects the Earth.
      - prompt: Tides
        worlds:
          NoMoon:
            feedback: Without the gravity of the moon the tides are a lot smaller than they are currently.



worlds:
  RocketLaunch:
    display_name: Rocket Launch
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -1731
    top_left_coordinate_z: 2638


  LunarCrater:
    display_name: Lunar Crater
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -222
    top_left_coordinate_z: -160

  Hub:
    display_name: Space Station
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -155
    top_left_coordinate_z: 10

  EarthControl:
    display_name: Earth Control
    pixel_to_block_ratio: 1
    top_left_coordinate_x: -251
    top_left_coordinate_z: -275

  NoMoon:
    display_name: No Moon
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -325
    top_left_coordinate_z: -304

  ColderSun_HabitableStrip:
    display_name: Colder Sun (Habitable Strip)
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -227
    top_left_coordinate_z: -256

  ColderSun_Cold:
    display_name: Colder Sun (Cold)
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -219
    top_left_coordinate_z: -137

  ColderSun_Hot:
    display_name: Colder Sun (Hot)
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -302
    top_left_coordinate_z: -215

  TiltedEarth_Frozen:
    display_name: Tilted Earth (Frozen)
    pixel_to_block_ratio: 1
    top_left_coordinate_x: -330
    top_left_coordinate_z: -200

  TiltedEarth_JungleIsland:
    display_name: Tilted Earth (Jungle)
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -301
    top_left_coordinate_z: -169

  TiltedEarth_Melting:
    display_name: Tilted Earth (Melting)
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -315
    top_left_coordinate_z: -244

  Mynoa_close:
    display_name: Mynoa (Close)
    pixel_to_block_ratio: 4
    top_left_coordinate_x: 1218
    top_left_coordinate_z: 786

  Mynoa_half:
    display_name: Mynoa (Half)
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -2480
    top_left_coordinate_z: 495

  Mynoa_far:
    display_name: Mynoa (Far)
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -81
    top_left_coordinate_z: -624

  Cancri:
    display_name: Cancri
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -21
    top_left_coordinate_z: -28

  Gliese:
    display_name: Gliese
    pixel_to_block_ratio: 1
    top_left_coordinate_x: -314
    top_left_coordinate_z: -257

  Trappist:
    display_name: Trappist
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -250
    top_left_coordinate_z: -216

  Kepler:
    display_name: Kepler
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -256
    top_left_coordinate_z: -256

  BrownDwarf:
    display_name: Brown Dwarf
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -301
    top_left_coordinate_z: -283

  TwoMoons:
    display_name: Two Moons
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -70
    top_left_coordinate_z: -50

  TwoMoonsLluna:
    display_name: Two Moons (Lluna)
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -100
    top_left_coordinate_z: -80

  TwoMoonsLow:
    display_name: Two Moons (Low)
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -70
    top_left_coordinate_z: -50

  BlackHole:
    display_name: Black Hole
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -120
    top_left_coordinate_z: -120

  ETLife:
    display_name: ET Life
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -49
    top_left_coordinate_z: -49


  Galaxy:
    display_name: Galaxy
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -270
    top_left_coordinate_z: -300

  NeutronStar:
    display_name: Neutron Star
    pixel_to_block_ratio: 4
    top_left_coordinate_x: -110
    top_left_coordinate_z: -110


  Quasar:
    display_name: Quasar
    pixel_to_block_ratio: 1
    top_left_coordinate_x: -340
    top_left_coordinate_z: -410

