mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: user
  password: pass

database: true
agent-worlds: None

worlds:
  NoMoon:
    display_name: No Moon
    pixel_to_block_ratio: 2
    top_left_coordinate_x: -325
    top_left_coordinate_z: -304
