name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Sam Hum
api-version: 1.13
main: edu.whimc.feedback.StudentFeedback
softdepend: [ProtocolLib]
commands:
  structureassessment:
    description: Assesses quality and structure of observation
    usage: '/structureassessment [observation] [observation type]'
  progress:
    description: Gives feedback on student progress during session
    usage: '/progress'
  leaderboard:
    description: Displays order of current players on server
    usage: '/leaderboard'
  agentdialogue:
    description: Displays dialogue with agent
    usage: '/agentdialogue'
