name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Sam Hum
api-version: 1.13
main: edu.whimc.feedback.StudentFeedback
softdepend: [ProtocolLib]
depend: [WHIMC-Observations, WHIMC-OverworldAgent]
commands:
  progress:
    description: Gives feedback on student progress during session
    usage: '/progress'
  leaderboard:
    description: Displays order of current players on server
    usage: '/leaderboard'
