name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Sam Hum
api-version: 1.13
main: edu.whimc.ObservationAssesser.ObservationAssesser
commands:
  observationassesser:
    description: Assesses quality and structure of observation
    usage: '/observationassesser [observation] [observation type]'
